services:
  site:
    user: nobody
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./laravel-app:/home/nobody/site
    command: sh -c "/usr/local/bin/init.sh"
